--- #YAML:1.0
name:               Regexp-Common-Chess
version:            0.1
abstract:           regexp for algebraic notation in chess
author:
    - Olof Johansson <olof@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Regexp::Common:  0
    Test::More:      0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
